### ISSUE TITLE
crosstab not supported error in Crhome v41.0.2272 - Windows 7 

### ISSUE THREAD

**Issue by KamalakannanPE** [tejacques/crosstab#20] opened 2015-03-23 06:13 UTC
Hi,
  I'm not sure why this happening, I'm using crosstab in my application. It works fine initially, but when the page load increases or if my application get crashed, crosstab is not working. It throws "crosstab not supported" error. Even after restarting the browser this issue is coming.

Steps to reproduce:

1. Open a page which uses crosstab
2. Open console, and run a infinite loop, now the application will crash.
3. Restart the browser and open the page
4. Observe the error

**Comment by tejacques** [comment] 2015-03-23 14:44
Hey @KamalakannanPE,

I think this most likely has to do with the `PING_TIMEOUT` being too low. I did encounter this on some slower machines while testing in VMs, but it's also possible this could happen if a lot of scripts are loaded after `crosstab`. In addition, once setup has completed once, the result on that domain will be cached in localStorage. You'll need to clear localStorage to get rid of the error.

If you're able to reliable reproduce this, I'd love to have the following information:

* Exact JS/HTML on the page your loading (ideally in a minimal reproduction)
* Machine processor (I.E. i7 5770)

I think I might add a diagnostics page to help decipher these problems in the future. I'll add a note to the issue about updating examples.

I'm about to bump the version which does have an increased `PING_TIMEOUT`, I'll ping you in this thread when that's release and you can check if that resolves your issue.

**Comment by tejacques** [comment] 2015-03-23 18:31
I pushes the latest version to npm -- try grabbing it and giving it another whirl

**Comment by tejacques** [comment] 2015-03-31 20:15
Closing this as I'm unable to reproduce. Please let me know if pulling latest fixed your issue.

**Closed by tejacques** 2015-03-31 20:15 UTC
